// <auto-generated />
namespace BlogsAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class imageAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202308260634248_imageAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
